workflow_get_inputs_resp_elem:
  - read:
      path: /workflows/v1/os.eda.nokia.com/v1alpha1/namespaces/{namespace}/deployimages/{name}/_input
      method: GET

workflow_input_data:
  - update:
      path: /workflows/v1/os.eda.nokia.com/v1alpha1/namespaces/{namespace}/deployimages/{name}/_input
      method: PUT

com.nokia.eda.os.v1alpha1.deploy_image:
  - create:
      path: /workflows/v1/os.eda.nokia.com/v1alpha1/namespaces/{namespace}/deployimages
      method: POST
  - read:
      path: /workflows/v1/os.eda.nokia.com/v1alpha1/namespaces/{namespace}/deployimages/{name}
      method: GET

com.nokia.eda.os.v1alpha1.deploy_image_list:
  - read:
      path: /workflows/v1/os.eda.nokia.com/v1alpha1/deployimages
      method: GET
  - read:
      path: /workflows/v1/os.eda.nokia.com/v1alpha1/namespaces/{namespace}/deployimages
      method: GET

totalPaths: 7
totalSchemas: 11
usedSchemas: 4
unusedSchemas: 7
unusedSchemaList:
  - ErrorIndex
  - ErrorItem
  - ErrorResponse
  - WorkflowId
  - WorkflowIdentifier
  - WorkflowInputDataElem
  - com.nokia.eda.os.v1alpha1.DeployImage_metadata
